language: python
python:
- '3.7'
install: 'pip install pybuilder '
script: pyb install_dependencies package -v -P build_number=0.1.${TRAVIS_BUILD_NUMBER}
deploy:
  provider: pypi
  user: alienvault_engineering
  distributions: sdist
  server: https://upload.pypi.org/legacy/
  skip_cleanup: true
  password:
    secure: Xt2DH6j0LegsVAJOq54Nh5nxMwmoLZYiiMxNrE3O62BURPg/9DeTDr1wwh4orMrx0fOQhDrV0FkwpHBlaqadWBMsTHEYssoal5f/G8Jdg5uxpg3hN4XEDPY0IH3KA92/ET4TVqkEK+Gfc9Ab1TfImpaCELDE4D1dv0afZ2ytkzXZPexa5QyxyEVB34umEAlQQl78WOKS5S3nOgBWx743834U5dSXDTTgMTMsTSikBnkAB8oZUa+Jq/JwaHCEm1T9rcl0mc8Xle3h5ki7oTB8IM/PeOVBST80sNNB27Y6JCO7xYBmBSXBpgYbI1nXBwtzhGaHyrYXV01gHnqPdyoLBjQnTpQJe3z8dOS3jLRSgiYH47YwBhzfhVJKP0qyLNjt5GVWEZJOuGKxiUP9pTEzfzg53/74/eTDaFxut3ywx+m4bnVivD4TnfPMWDaqAoW+jxa5IztKbY4mmrRe4QpEJ0ByYoUzy0tfKjqmV4SIgCCUqKrAy35F5cJ2cNBdgGMbNfmBKPurrgiotZG04WWmatlYAYX9lcK3ivdW1exL46BxFUxluqO+oVMNsLm6mXmONeCbh7rsZE712RxOmkPdv07okHFoJZHq0pPISkvDslc/ZfQ3dOC9Cq3Uy0a4GBm3RyuuxOREoVE1mqVYRLuaE3b7iZsAb0wMmblHtRNqN5k=
