language: python
python:
- '2.7'
install: 'pip install pybuilder '
script: pyb install_dependencies package   -P build_number=0.1.${TRAVIS_BUILD_NUMBER}
deploy:
  provider: pypi
  user: alienvault_engineering
  distributions: sdist
  server: https://upload.pypi.org/legacy/
  password:
    secure: v0ydV20nJZdMSaZ7qe0hKGPEJ8223ClnCyhPRIa6WKkoPrrzWCuwRvsx+RBK4mpjjV+YWkcW4xtyL5CXRedoS286h1a/mrsx7nlEvmmg8KC6YCpsbX0ALM6tpprnGt0+S80A+3gcALKsYpkDh3L6OnCEYEhZg978u67WRs0Ccd9jEMumhh7zM55FnjlXS3kqKYSgWHHwEYlmn8MoBRZJMVSt5tjV5kEfwkH55vlsfmp/2JNdWS32P/v+7I37WXR4VMRywFl0GjCstiE6Ber5jgN5m9RVEswFXnxgFy1/JHzWrArL27GuDH6yE1yzEkRDcaqAdS9ifrY28nldumkVyn80St02zsgRZGAK9ffb95qPXTl9WGzfjRfy+TizyUpaFMah9oH8TNFfWavQQUMMyad0GsjldDI181R+j3UGu29b1+0czDieTf95UnQusRHpxsO7WRyzjoztQObbOme6iSD/jyHviIYw5dvEe4ghSR79TaFyKuFETsuvnCMZLpOEmLQU1lILG0qBP5uEApBR7ztI9IT9MWL32GcrSHue5VI1G3Myr0ngmxS40wAk37j6wmeNiOGY9WjoSf/uFqRVSkaJ+ZazN4sSORATHwViiNy8yW5BhN42AtkZGILSaB533WSH0Sko0sPaDn0j3L3yU/sFvjVfNwcJiq3XHmCz05Y=
