language: python
python:
- '2.7'
install: 'pip install pybuilder '
script: pyb install_dependencies package   -P build_number=0.1.${TRAVIS_BUILD_NUMBER}
deploy:
  provider: pypi
  user: alienvault_engineering
  distributions: sdist
  server: https://upload.pypi.org/legacy/
  password:
    secure: JmpFamKuePLgFjFiwO7kVYZLigxOSk/XKmHEeIAnckzJf5P+5zUrLKS0RgdS0B19REdglxMAmJi9wCNy0lJgPy2rfA1xv8CsjOm2Sr3ry/mPWucrn2oDORk+Nqt5zsy27ryLSjNkvRCC8pBhleVbKUSMB+4HS0qv8VRLl3w1GqJ19gJsfaqAlxTqnB6PflfKXTNCgXrmeUxwTaB8yLwNtkYo7mEvXT3LJPqtQjCPEM7YyKHxzaOCtucIO7m0a5n27LkJAxIG12H4a6yspGYr2oJqZYbXUQkLeDjxQnS55zlnXdYGCqjdIi8FuG5DZ+/qnZ/CehNeqUfLh6M1b5Vr1kNvYS8RSpw8dG7tWyEs4APcYFpnfoAqdxAHUBZ+nJBJVJPsEbPgoGIG5ic35rhp7xQU6+ZvZ7Xarvzl7dmivlfHg367mIe5vUqRAtkZ4xHQW2IRMaqWAyJUuvf8ZhBEA8UlAYVlZIw4P0d1Hvf/esBfpBW6I1sxdOixqE40rC/MVlc7Jx4EnOCRPRs5snw260ne9XgscLyiEjAdlAiMrKUf8EHgXHcCBfEVYOfYTDqQU9PkZXTJwHU47tQNwX1gIOvGpCZWcMrORMG02kU6wV41l4ZIcVTsjKDGIWPwSskVvWUVh+8Smo7ml7yTbNAwtVxwdj79oLbsedlfo/IIDIA=
